### ISSUE TITLE
Replace symlinking with copying

### ISSUE THREAD

**Issue by tatahin** [genome/analysis-workflows#691]
Hello!
The following files contain `ln -s` command:
```
index_bam.cwl
index_cram.cwl
```
When running them with `cwltool` resulting output directory doesn't contain symlinks. I suggest to replace `ln -s` with `cp` for better compatibility with the reference implementation. What do you think about it?

**Comment by susannasiebert** [comment]
The `ln -s` in the `pvac*.cwl`s doesn't pertain to symlinking output files. It's to symlink TMPDIR to a clean location because otherwise we were getting error of the TMPDIR path being too long in cromwell executions where the TMPDIR for each step is nested very deep in the output directory structure. Further down in the `arguments` you will see it calling the actual pvac* commands.

**Comment by tatahin** [comment]
@susannasiebert, thank you! I hurried a bit after checking first two files... Updated the issue.

**Comment by tmooney** [comment]
I've opened #692, which includes a proposed solution to this issue.
