### ISSUE TITLE
sh error "1 not found"

### ISSUE THREAD

**Issue by serge2016** [genome/analysis-workflows#839]
The first part of the base command doesn't work:
https://github.com/genome/analysis-workflows/blob/295e7b7f51727c0f2d6cc86ce817449b2e8dba3c/definitions/tools/cnvnator.cwl#L7

**Comment by tatahin** [comment]
When we tried to start cnvnator with escape "$" in ${SAMPLE}, there is the error:
```
'source' '/opt/root/bin/thisroot.sh' && '/bin/bash' 'run_cnvnator.sh' '/var/lib/cwl/stg3a3d11b2-e63c-42de-bc0c-200400b6cf0b/2895499237.bam' '100' 'chr1 chr2 chr3 chr4 chr5 chr6 chr7 chr8 chr9 chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 chr20 chr21 chr22 chrX chrY' '/var/lib/cwl/stge06e1f61-a72b-43dc-a583-21fda44505cf/chr17_test.fa' 'serge_sample1'
/bin/sh: 1: source: not found
```

**Comment by tmooney** [comment]
`source` is a `bash` keyword, but `cwltool` is using `/bin/sh` as its shell :
https://github.com/common-workflow-language/cwltool/blob/cf9d7cdefa6dfb3b678636da02bc55b6108c04ac/cwltool/command_line_tool.py#L618

The simple fix would be to switch to `.` instead of `source`, but it looks like `/opt/root/bin/thisroot.sh` might have at least one thing in it that also doesn't work with `/bin/sh`, so fixing that will be slightly more complicated.
