### ISSUE TITLE
somatic_llr and other filters in low tumor cellularity samples - tumor purity not exposed

### ISSUE THREAD

**Issue by boyangzhao** [genome/analysis-workflows#847]
I'm running on the somatic exome pipeline and noticed that for samples with low purity, a substantial of the variants are filtered out by somatic_llr (in the filter_vcf -> filter_vcf_somatic_llr) step (I have llr threshold set at 5). I noticed that the python code somatic_llr_filter.py has options for the normal-contamination-rate and tumor-purity fields, but in the CWL, these are not exposed so it's using the defaults (0 and 1, respectively). I'm wondering if the filter_vcf_somatic_llr and more generally the other filters (e.g. depth, which I have at 20) in the pipeline work for low purity samples?

Was there a reason the purity/contamination parameters not exposed in the cwl? Are there other workflows that are used independently to handle low purity samples?

**Comment by chrisamiller** [comment]
Yes, the LLR filter could use additional documentation and additional options exposed.  The easiest way to handle low-purity samples is to drop that LLR score to something lower (the values are in the output VCF, you'll just have to modify the flags or re-run those last few steps)

In my experience, I'd be hesitant to go much below 3, as at that point, the false positive rate gets quite high. For samples with high purity (>80), I generally use a threshold of 10, which results in a very low false positive rate.  The default of 5 is something of a compromise position.  

I'm making a note to add some more documentation around this soon

**Comment by boyangzhao** [comment]
Thank you Chris! Do you also lower the DEPTH as well in case of lower purity? I think default in cwl was at 1, and I have mine at 20. Also, is there a publication or some documentation that talks a bit more about the somatic LLR rationale and the mathematics behind it?

**Comment by chrisamiller** [comment]
Yeah, that really depends on the goals of the experiment.  In research pipelines, we usually set the depth filter to 1, because the variant callers and llr filter generally are not letting anything through with marginal depth anyway.  For some assays, (like our CLE assay that uses parts of this pipeline), the depth filter is applied, with a setting of 20.

The LLR filter is not well documented, except in the code, which can be found here:
https://github.com/genome/docker-somatic-llr-filter/blob/master/somatic_llr_filter.py

The gist is that it's calculating the probability that a site is somatic, given just the support observed in the tumor and normal. It's not a true somatic variant caller, but we find that it works well as a filter to remove sites with scant evidence.  It can be treated as way to dial in a desired level of sensitivity/specificity, given variant calls as input. 

As a back-of-the-envelope rule, for a pure tumor with a clean normal, a setting of 10 will return calls that require almost no manual review, a setting of 5 will include some more questionable sites, and a setting of 3 will return a more comprehensive list that requires extensive review.  In impure tumors, yes, either lower LLR settings, or explicitly specifying the input purities is something that needs to be done. 

I'll leave this issue open until a) the the purity parameter is exposed and b) some documentation has been added.  If you're running the pipeline now and need the param exposed ASAP, feel free to make a pull request with that change!

**Comment by chrisamiller** [comment]
This was fixed in https://github.com/genome/analysis-workflows/pull/946  Thanks for the feedback!
